baseURL = "https://bilguunbyambadorj.netlify.app/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "sada"

[params]
  author = "Bilguun Byambadorj"
  description = "My Resume"

[build]
  ignoreErrors = ["error-disable-taxonomy"]